name: i_am_rich
description: A new Flutter project.

publish_to: 'none' #not included in video tutorial
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0 #not included in video tutorial

flutter:
  uses-material-design: true
  assets:
    - images/diamond.png
